name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      actions: write
    env:
      GH_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        package_manager: [yarn]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: ${{ matrix.package_manager }} install

      - name: Build Electron app
        run: npm run make

      - name: Package Electron app
        run: npm run package

      - name: Publish Electron app
        run: npm run publish

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4.4.0
        with:
          name: release-artifacts
          path: out/make

      - name: Verify zip files exist
        run: |
          if [ ! -f "out/make/*.zip" ]; then
            echo "No zip files found in out/make/. Exiting."
            exit 1
          fi

      - name: Publish Release
        run: |
          gh release create ${{ github.ref_name }} $(ls out/make/*.zip) --generate-notes --title "Version ${{ github.ref_name }}"
