name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        package_manager: [npm, yarn]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: ${{ matrix.package_manager }} install

      - name: Build Electron app
        run: npm run make

      - name: Install RPM and DEB build dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot dpkg

      - name: Install Squirrel dependencies (Windows only)
        if: matrix.os == 'windows-latest'
        run: choco install squirrel.windows

      - name: Package Electron app
        run: npm run package

      - name: Publish Electron app
        run: npm run publish

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: out/make
