name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      actions: write

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        package_manager: [npm, yarn]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: ${{ matrix.package_manager }} install

      - name: Build Electron app
        run: npm run make

      - name: Package Electron app
        run: npm run package

      - name: Publish Electron app
        run: npm run publish

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4.4.0
        with:
          name: release-artifacts
          path: out/make

      - name: Publish Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: out/make/*
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.sha }}
          body: |
            This is an automated release.
            It contains the latest changes from the main branch.
            Please refer to the commit history for more details.
          draft: false
          prerelease: false
